package com.kinto2517.weatherapp.Mapper;

import com.kinto2517.weatherapp.Dto.WeatherDTO;
import com.kinto2517.weatherapp.Dto.WeatherSaveRequest;
import com.kinto2517.weatherapp.Entity.Weather;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.ReportingPolicy;
import org.mapstruct.factory.Mappers;

import java.util.List;

@Mapper(unmappedTargetPolicy = ReportingPolicy.IGNORE)
public interface WeatherMapper {

    WeatherMapper INSTANCE = Mappers.getMapper(WeatherMapper.class);

    @Mapping(target = "id", ignore = true) // Ignore mapping for 'id' field as it will be generated by the database
    Weather convertToWeather(WeatherSaveRequest weatherSaveRequest);

    @Mapping(source = "city.id", target = "cityId") // Map the city's id to cityId property
    WeatherDTO convertToWeatherDTO(Weather weather);

    List<WeatherDTO> convertToWeatherDTOs(List<Weather> weathers);


}
